### ISSUE TITLE
Failing to build with gcc 4.7 

### ISSUE THREAD

**Issue by mansoor-s** [aras-p/glsl-optimizer#9]
Hello,

My build failed with the error:

``` bash
aras-p-glsl-optimizer-f2217b0/tests/glsl_optimizer_tests.cpp:250:22: error: ‘unlink’ was not declared in this scope
make[2]: *** [CMakeFiles/glsl_test.dir/tests/glsl_optimizer_tests.cpp.o] Error 1
make[1]: *** [CMakeFiles/glsl_test.dir/all] Error 2
make: *** [all] Error 2
```

Fix: add unistd.h  to /tests/glsl_optimizer_tests.cpp for non-windows builds

http://gcc.gnu.org/gcc-4.7/porting_to.html

Cheers
